### ISSUE TITLE
Aktivitätendiagramm zu User Story 1 erstellen

### ISSUE THREAD

**Issue by Grabkaazz** [colichri/web-programming#10]

**Comment by Milan-Je** [comment]
[Akteure.docx](https://github.com/colichri/web-programming/files/12876533/Akteure.docx)

**Comment by Milan-Je** [comment]
![User Story 1](https://github.com/colichri/web-programming/assets/144894730/319ddc65-8ea3-439d-9e43-29ae3796bd7f)

**Comment by Milan-Je** [comment]
[Aktivitätsdiagramm User Story 1.zip](https://github.com/colichri/web-programming/files/12928145/Aktivitatsdiagramm.User.Story.1.zip)
